Invoke-Expression(Invoke-WebRequest "https://raw.githubusercontent.com/carlbennett-ar/ManualModTestScripts/master/per-userEnvVars.ps1")
Invoke-Expression(Invoke-WebRequest "https://raw.githubusercontent.com/carlbennett-ar/ManualModTestScripts/master/per-userFiles.ps1")
Invoke-Expression(Invoke-WebRequest "https://raw.githubusercontent.com/carlbennett-ar/ManualModTestScripts/master/per-userINI.ps1")
Invoke-Expression(Invoke-WebRequest "https://raw.githubusercontent.com/carlbennett-ar/ManualModTestScripts/master/per-userReg.ps1")
Invoke-Expression(Invoke-WebRequest "https://raw.githubusercontent.com/carlbennett-ar/ManualModTestScripts/master/per-userShortcut.ps1")